language: node_js
node_js:
  - "12"
jobs:
  include:
    - stage: "Tests"                # naming the Tests stage
      name: "Unit Tests"            # names the first Tests stage job
      script: npm test
    - script: npm run test:int
      name: "Integration Tests"
