version: '3'

services:
  api-boilerplate:
    image: api-boilerplate
    build:
      context: .
      args:
        NODE_ENV: development
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    command: npm run dev -- --inspect=0.0.0.0:9229
